### PR TITLE
fix: remove special handling of sourceType for TypeScript parser

### LINKED ISSUE #891: Suggestion: Move `languageOptions` properties from nested `parserOptions`
### What problem do you want to solve?

Currently the playground generates a configuration which specifies `sourceType` and `ecmaVersion` in `languageOptions.parserOptions` instead of `languageOptions`. For example:
```javascript
export default [
    {
        "languageOptions": {
            "parserOptions": {
                "ecmaFeatures": {
                    "jsx": true
                },
                "sourceType": "module"
            },
        }
    }
];
```

### What do you think is the correct solution?

Move the properties `languageOptions.parserOptions.{sourceType,ecmaVersion}` to `languageOptions.{sourceType,ecmaVersion}`.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

This change would be consistent with the [documentation](https://eslint.org/docs/latest/use/configure/language-options#specifying-javascript-options)

### PR DESCRIPTION
**Pull request by DMartens**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?
Removing the special behaviour for the TypeScript parser.

#### What changes did you make? (Give an overview)
This PR includes two fixes:
1. remove the hardcoded `sourceType` of "module" for the TypeScript parser (refs #910)
2. Fixes #891 by setting the `sourceType` on `languageOptions` instead of `languageOptions.parserOptions` when swapping the parser.

#### Related Issues
Fixes #891 and #910.

#### Is there anything you'd like reviewers to focus on?
Please also try various variations of updating the configuration and the resulting configuration file.

### CODE REVIEW

File: src/playground/app.jsx
Comment (Tanujkanti4441) [inline src/playground/app.jsx]: Screenshot 2026-01-20 225100

The `Source Type` dropdown is not selecting any option, even after clicking on the option. Can you fix that?

File: src/playground/components/configuration.jsx [hunk 1]
```diff
@@ -532,8 +532,6 @@ export default function Configuration({
 											selected.value;
 										delete newOptions.languageOptions
 											.sourceType;
-										newOptions.languageOptions.parserOptions.sourceType =
-											"module";
```
Comment (Tanujkanti4441) [inline src/playground/components/configuration.jsx]: Currently, we are setting `Source Type` to `module` when selecting `@typescript-eslint/parser` then user can select any `Source Type` they want. Can we retain this behavior?

**Review by Tanujkanti4441 — CHANGES_REQUESTED** [review]
Thanks for the PR.

**Review by Tanujkanti4441 — COMMENTED** [review]
Image

Right now on selecting `@typescript-eslint/paser` the `Source Type` option is empty, as  https://github.com/eslint/eslint.org/pull/915#discussion_r2725504081 suggests to use the default value for `sourceType`, so can we also add `(default)` option on `Source Type` for tsparser as well like we have for espree?

File: src/playground/components/configuration.jsx [hunk 2]
```diff
@@ -391,28 +385,13 @@ export default function Configuration({
...
-										? sourceTypeOptionsForTypeScriptParser
-										: sourceTypeOptions
-								}
+								value={sourceTypeOptions.filter(
+									sourceTypeOption =>
+										sourceTypeOption.value ===
+										(options.languageOptions?.sourceType ||
+											"default"),
+								)}
+								options={sourceTypeOptions}
```
Comment (Tanujkanti4441) [inline src/playground/components/configuration.jsx]: Getting this error in playground.

Image

steps to reproduce
1. Select the `@typescript-eslint/parser`, the sourceType will be (default) here.
2. Then select any other source type like `script`.
3. Select the (default) again.

Note:- I tried to run the changes in this PR locally, as I am not able to see the playground using the deploy link.
