### PR TITLE
fix: fallback images on site

### LINKED ISSUE #679: Bug: error in images fetched from github
### URL(s)

https://eslint.org/team/
https://eslint.org/sponsors/
other

### What did you do?

went to the website.

### What did you expect to happen?

there must be the images of sponsors, authors and team members.

### What actually happened?

most of the images were not there.
Image
Image
Image

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

All the images with issue are sourced from github and were updated in 
https://github.com/eslint/eslint.org/commit/45a54f8022b38a8b7b5635c8e44f417659eb4962

### PR DESCRIPTION
**Pull request by Tanujkanti4441**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?
Constructing old avatar url from the new one.  

#### What changes did you make? (Give an overview)
Did omit the `private-` word and `jwt` token from the URL of image fetched from github.

#### Related Issues
Fixes #679

### CODE REVIEW

**Review by amareshsm — APPROVED** [review]
LGTM. Thanks. Leaving it open for 2nd review.

File: tools/add-author.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ async function fetchUserProfile() {
 		name: profile.name,
 		title: "Guest Author",
 		website: profile.blog,
-		avatar_url: profile.avatar_url,
+		avatar_url: `${profile.avatar_url.replace("private-", "").split("?")[0]}?v=4`,
```
Comment (amareshsm) [inline tools/add-author.js:49]:
```suggestion
		avatar_url: `${profile.avatar_url.replace("private-", "").split("?")[0]}?v=4`,
```
We could consider adding a fallback image in case the actual image isn't found, though I'm not sure if GitHub itself provides a fallback image.

Comment (Tanujkanti4441) [reply tools/add-author.js:49]: sounds good to me, should we use the fallback image which we are using for sponsors? this one
Screenshot 2024-12-21 170645

Comment (amareshsm) [reply tools/add-author.js:49]: I am 👍 let's get other's opinions too.

Comment (harish-sethuraman) [reply tools/add-author.js:49]: This fallback also looks good to me.

File: tools/fetch-team-data.js [hunk 2]
```diff
@@ -96,7 +96,7 @@ async function fetchUserProfile(username) {
 			: profile.blog
 				? `https://${profile.blog}`
 				: profile.blog,
-		avatar_url: profile.avatar_url,
+		avatar_url: `${profile.avatar_url.replace("private-", "").split("?")[0]}?v=4`,
```
Comment (mdjermanovic) [inline tools/fetch-team-data.js:99]: Can we extract this into a shared place (e.g., `tools/utils.js`) as a function so that we don't have to repeat the same logic in multiple files?

Comment (mdjermanovic) [inline tools/fetch-team-data.js:99]: Some URLs have `u` parameter:

https://github.com/eslint/eslint.org/blob/617c1962e2b99163cf69f6ad217eea5e7d9a441c/src/_data/sponsors.json#L76-L77

Any ideas about what it represents?

Should we maybe remove just the `jwt` parameter and leave the others?

Comment (Tanujkanti4441) [reply tools/fetch-team-data.js:99]: >Some URLs have u parameter:

Can it stands for unique? even though without this parameter the results are same.

Also seems links are already fixed by commit https://github.com/eslint/eslint.org/commit/e385d5fc1a47df1d491509c4aabf754459bb5d42 should we still apply this fix?

Comment (amareshsm) [reply tools/fetch-team-data.js:99]: > Also seems links are already fixed by commit [e385d5f](https://github.com/eslint/eslint.org/commit/e385d5fc1a47df1d491509c4aabf754459bb5d42) should we still apply this fix?

I also noticed that it might be a good idea to wait a couple of days. If GitHub is still testing features with a subset of users, it could potentially break again. As of now, we might not be part of the experiment, but if they do a full rollout, we could be impacted.

Comment (mdjermanovic) [reply tools/fetch-team-data.js:99]: I think it would be good to continue working on this PR and have it ready (or perhaps even merge it) in case the problem happens again. Unless they've decided not to continue with the change, but I couldn't find any mention of that in https://github.com/orgs/community/discussions/147297.

File: tools/add-author.js (hunk 1 above)
Comment (Tanujkanti4441) [reply tools/add-author.js]: Added fallback image.

File: tools/fetch-team-data.js (hunk 2 above)
Comment (Tanujkanti4441) [reply tools/fetch-team-data.js]: Done! `tools/utils.js` has been created.

Comment (Tanujkanti4441) [reply tools/fetch-team-data.js]: >Should we maybe remove just the jwt parameter and leave the others?

should we work on this approach? as we can see both links with and without u token gives the same result:
[`https://avatars.githubusercontent.com/u/53535748?u=d1e55d7661d724bf2281c1bfd33cb8f99fe2465f&v=4`](https://avatars.githubusercontent.com/u/53535748?u=d1e55d7661d724bf2281c1bfd33cb8f99fe2465f&v=4)

[`https://avatars.githubusercontent.com/u/53535748?v=4`](https://avatars.githubusercontent.com/u/53535748?v=4)

Comment (amareshsm) [reply tools/fetch-team-data.js]: I think it's better to remove the JWT parameter and retain the others.

**Comment by nzakas** [comment]
I think this is a bit more complicated than we need. We can easily calculate the correct URL in our fetch scripts by using the user's ID. I put this together:
https://github.com/eslint/eslint.org/pull/683

**Comment by Tanujkanti4441** [comment]
> I think this is a bit more complicated than we need. We can easily calculate the correct URL in our fetch scripts by using the user's ID. I put this together: #683

So, i think i should revert the avatar link related changes and keep only fallback related changes here?

**Comment by nzakas** [comment]
I'm not sure we need the fallback changes.

File: src/_includes/components/card.macro.html [hunk 3]
```diff
@@ -43,7 +43,8 @@ <h3 class="card__title">
             {{ params.teaser }}
         </p>
         <div class="card__footer">
-            <img class="blog-post__author-photo" src="{% if params.authorImage %}{{ params.authorImage }} {% else %}../../../assets/images/people/_placeholder-avatar.svg{% endif %}" alt="{{ params.authorName }}" width="40" height="40" loading="lazy">
+            {% set fallback_image = '/assets/images/people/_placeholder-avatar.svg' %}
+            <img class="blog-post__author-photo" src="{{ params.image if params.image else fallback_image }}" alt="{{ params.authorName }}" width="40" height="40" loading="lazy" onerror="this.src = '{{fallback_image}}'">
```
Comment (Tanujkanti4441) [inline src/_includes/components/card.macro.html:47]: >I'm not sure we need the fallback changes.

We can see here a fallback image is already applied but actually it's not working, can it be considered as a bug?

Comment (nzakas) [reply src/_includes/components/card.macro.html:47]: Yes, I think that can be considered a bug. I just don't think we need to add fallback images to places where we didn't have them before.

Comment (amareshsm) [reply src/_includes/components/card.macro.html:47]: I guess the fallback image was working as intended.

Comment (Tanujkanti4441) [reply src/_includes/components/card.macro.html:47]: Fallback images was only working for sponsors in `All backers` section as you can see in images provided in issue template of https://github.com/eslint/eslint.org/issues/679

Comment (Tanujkanti4441) [reply src/_includes/components/card.macro.html:47]: >I just don't think we need to add fallback images to places where we didn't have them before.

reverted the changes.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!
